version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - API_V1_STR=/api/v1
      - PROJECT_NAME=SpaceX Dashboard API
      - SPACEX_API_URL=https://api.spacexdata.com/v4